name: Setup Node.js with Pnpm
inputs:
  node-version:
    description: 'The Node.js version to use'
    required: true
    default: '20'
  pnpm-version:
    description: 'The Pnpm version to use'
    required: true
    default: '9'
  run-install:
    description: 'Whether to run `pnpm install`'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Setup Pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: false
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
        cache-dependency-path: 'pnpm-lock.yaml'
    - name: Run pnpm install
      if: ${{ inputs.run-install }}
      shell: bash
      run: pnpm install --frozen-lockfile
